map01 = ['baaaaaabaaaaaaaa',
         'baaaaaaaaabaaaaa',
         'bacaaaaaaabaaaaa',
         'bbbbbabbbbbaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',]
