map01 = ['baaaaaabaaaaaaaa',
         'bacaaabaaabaaaaa',
         'baaaabaaaabaaaaa',
         'bbbbbbbbbbbaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',
         'aaaaaaaaaaaaaaaa',]
