map01 = ['baaaaaaaaaaaaaaa',
         'baaaaaaaaaaaaaaa',
         'aacaaaaaaaaaaaaa',
         'aaaaabbbaaabbaaa',
         'bbbbaaabbbbbbaaa',
         'aaabaaaaaaabbbaa',
         'aaabbaaaaaabbaaa',
         'aaaabaabaaaaaaab',
         'bbaaaabbaaaaaaaa',
         'abaaaabbaabbbbaa',
         'abbbbbbbaaaaaaab',
         'aaaaaaabbbbbbbbb',]
